### ISSUE TITLE
Cannot load events due to missing "data.name".

### ISSUE THREAD

**Issue by michael2221807** [LakhindarPal/discord-player-bot#148]
**Describe the bug**
Cannot load events due to missing "data.name". I did `npm run register` and `npm install` and all the event files seems to be in correct format. But getting this error when starting the app. If you have some time please help, Thanks!

**To Reproduce**

1. `npm install`
2. `npm run register`
3. `npm start`

**Screenshots**
I also printed out the list of event it gets from `sync()`, it appears that some of them are fine..
![image](https://github.com/LakhindarPal/discord-player-bot/assets/16907073/c5a53bba-b3e1-4199-bf17-c9db503f55cf)

**Additional Information:**
file:///home/pi/discord-player-bot/src/handlers/event.js:13
      throw new TypeError(
            ^

TypeError: The event at src/events/player/willAutoPlay.js is missing a required "data.name" property.
    at loadEvents (file:///home/pi/discord-player-bot/src/handlers/event.js:13:13)
    at async file:///home/pi/discord-player-bot/src/index.js:30:1

- OS: Linux
- nodejs version  v20.15.0
- Package Manager [e.g. npm 10.5.2]

**Comment by Crisstiian2303** [comment]
i got the same issue, how did you solve it? (reply here or write me a msg on discord. dis id: crisstiian)

**Comment by michael2221807** [comment]
> i got the same issue, how did you solve it? (reply here or write me a msg on discord. dis id: crisstiian)

I realized that the `npm i` missed some dependencies. Try this: `npm i opusscript  npm i node-opus  npm i @discordjs/opus`  before running it.

**Comment by Crisstiian2303** [comment]
> > i got the same issue, how did you solve it? (reply here or write me a msg on discord. dis id: crisstiian)
> 
> I realized that the `npm i` missed some dependencies. Try this: `npm i opusscript npm i node-opus npm i @discordjs/opus` before running it.

i think that will not work for me, because im on rocky linux arm aarch64 :sob:

**Comment by michael2221807** [comment]
> > > i got the same issue, how did you solve it? (reply here or write me a msg on discord. dis id: crisstiian)
> > 
> > 
> > I realized that the `npm i` missed some dependencies. Try this: `npm i opusscript npm i node-opus npm i @discordjs/opus` before running it.
> 
> i think that will not work for me, because im on rocky linux arm aarch64 😭

Interesting, I am using a raspbery pi 4 to host it, also a arm cpu

**Comment by Crisstiian2303** [comment]
> > > > i got the same issue, how did you solve it? (reply here or write me a msg on discord. dis id: crisstiian)
> > > 
> > > 
> > > I realized that the `npm i` missed some dependencies. Try this: `npm i opusscript npm i node-opus npm i @discordjs/opus` before running it.
> > 
> > 
> > i think that will not work for me, because im on rocky linux arm aarch64 😭
> 
> Interesting, I am using a raspbery pi 4 to host it, also a arm cpu

i found that i can install only 2 of 3 of the packages that you told me to install, Apparently I can't install discordjs/opus, I get an error and I've looked for a way to solve it and I can't find a way, I've changed my version of Nodejs to 18.20.2, and I've updated my python to 3.9.18, I honestly don't know what do XD 👍
